### ISSUE TITLE
Reporter.java Git problems

### ISSUE THREAD

**Issue by exception** [q8minecraft/EasyReporter#3]
Seems like you did something wrong whilst doing the Git pull/fetch and your Reporter.java file got corrupted, you can see the problems here:
- https://github.com/q8minecraft/EasyReporter/blob/master/src/Reporter.java#L94
- https://github.com/q8minecraft/EasyReporter/blob/master/src/Reporter.java#L104

**Comment by ProfessorZed** [comment]
Yea I had a bit of issues while pushing it, I'll try fixing that in a few minutes, thanks!

**Comment by ProfessorZed** [comment]
I'm currently experiencing issues opening my project on eclipse, it says "The project description file (.project) for 'Reporter' is missing.  This file contains important information about the project.  The project will not function properly until this file is restored." Any idea how to fix this ?

**Comment by exception** [comment]
Not really sure for that, i myself use IntelliJ, i'd recommend you use that too, might take some time to get used to it but trust me, it's soo much better. Maybe try this? stackoverflow.com/questions/5019929/eclipse-restore-missing-projects
